from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib import colors
from datetime import datetime
import io
import logging

logger = logging.getLogger(__name__)

class PDFRecipeGenerator:
    def __init__(self):
        self.page_width, self.page_height = letter
        self.styles = getSampleStyleSheet()
        self._create_custom_styles()
    
    def _create_custom_styles(self):
        """Create custom paragraph styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#FF6B6B'),
            spaceAfter=12,
            alignment=1
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#4ECDC4'),
            spaceAfter=10,
            spaceBefore=10
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['Normal'],
            fontSize=11,
            alignment=4
        ))
    
    def generate_pdf(self, recipe_data: dict) -> bytes:
        """Generate PDF from recipe data"""
        try:
            buffer = io.BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=letter)
            story = []
            
            story.append(Paragraph(recipe_data.get('name', 'Recipe'), self.styles['CustomTitle']))
            story.append(Spacer(1, 0.3*inch))
            
            if recipe_data.get('description'):
                story.append(Paragraph(
                    recipe_data['description'],
                    self.styles['CustomBody']
                ))
                story.append(Spacer(1, 0.2*inch))
            
            story.append(Paragraph("Ingredients", self.styles['CustomHeading']))
            ingredients_text = "<br/>".join([
                f"• {ing}" for ing in recipe_data.get('ingredients', [])
            ])
            story.append(Paragraph(ingredients_text, self.styles['CustomBody']))
            story.append(Spacer(1, 0.2*inch))
            
            if recipe_data.get('nutrition'):
                story.append(Paragraph("Nutritional Information", self.styles['CustomHeading']))
                nutrition_data = recipe_data['nutrition']
                nutrition_text = f"""
                <b>Calories:</b> {nutrition_data.get('calories', 'N/A')} | 
                <b>Protein:</b> {nutrition_data.get('protein', 'N/A')} | 
                <b>Carbs:</b> {nutrition_data.get('carbs', 'N/A')} | 
                <b>Fat:</b> {nutrition_data.get('fat', 'N/A')}
                """
                story.append(Paragraph(nutrition_text, self.styles['CustomBody']))
                story.append(Spacer(1, 0.2*inch))
            
            story.append(Paragraph("Instructions", self.styles['CustomHeading']))
            instructions_text = "<br/><br/>".join([
                f"<b>Step {i+1}:</b> {step}" for i, step in enumerate(recipe_data.get('instructions', []))
            ])
            story.append(Paragraph(instructions_text, self.styles['CustomBody']))
            story.append(Spacer(1, 0.2*inch))
            
            if recipe_data.get('tips'):
                story.append(Paragraph("Chef's Tips", self.styles['CustomHeading']))
                tips_text = "<br/>".join([f"• {tip}" for tip in recipe_data['tips']])
                story.append(Paragraph(tips_text, self.styles['CustomBody']))
            
            story.append(Spacer(1, 0.2*inch))
            generated_date = datetime.now().strftime("%Y-%m-%d %H:%M")
            footer = f"<i>Generated by AI Recipe Generator on {generated_date}</i>"
            story.append(Paragraph(footer, self.styles['Normal']))
            
            doc.build(story)
            buffer.seek(0)
            return buffer.getvalue()
        except Exception as e:
            logger.error(f"Error generating PDF: {str(e)}")
            raise